id: A453659C3
title: f185F
type: translation
source_metadata:
  languages:
  - sa
  - en
  - bo
  - zh
  datatype: PlainText
  created_at: 2022-05-27 15:37:18.875623
  last_modified_at: 2022-05-27 15:37:18.875626
